# Using $(extra-y) so Makefile.build and Makefile.clean know
# what they should do.

# $(head-y) Part
extra-y := head_32.o

# Linker Script
extra-y += vmSandix.ld

# built-in
obj-y := entry.o
obj-y += setup.o
