#ifndef _ASM_DESCRIPTOR_H_
#define _ASM_DESCRIPTOR_H_

/*
 * NOTE 1:
 *
 *	The processor check the DPL of the interrupt or trap gate
 *	only if the interrupt or exception is generated by INT X.
 *	The CPL must be less than or equal to the DPL of the gate.
 *
 *	For hardware-generated interrutps and processor-deteced
 *	exceptions, the processor ignores the DPL of the gates.
 *
 * NOTE 2:
 *
 *	The only difference between trap and interrupt gates is the
 *	way the processor handles the IF flags in EFLAGS register.
 *
 *	Through a interrupt gate, the processor clears the IF flag
 *	to prevent other interrupts from interfering with the current
 *	interrupt handler. A subsequent IRET instruction restores
 *	the IF flag to its value in the saved contents of the EFLAGS
 *	register on the stack.
 *
 *	Through a trap gate, it does not affect the IF flag.
 */

static inline void
_set_gate(unsigned int n, unsigned int addr, int type, int dpl)
{
	asm volatile (
		
	);
}

static inline void
set_trap_gate(unsigned int n, unsigned int addr)
{
	_set_gate();
}

static inline void
set_interrupt_gate(unsigned int n, unsigned int addr)
{
	_set_gate();
}

static inline void
set_system_trap_gate(unsigned int n, unsigned int addr)
{
	_set_gate();
}

#endif /* _ASM_DESCRIPTOR_H_*/
